---
# mapping sample
apiVersion: waas.radware.com/v1beta1
kind: Mapping
metadata:
  annotations:
    radware/generationNumber: "18797"
  name:  radware
  namespace: test
  labels:
    release: waas
spec:
  operatorEmail: fimal@radware.com
  maps:
  - domains:
    - hackazon-king-demo.com
    - hackazon-king-demo.com:*
    operatorEmail: "fimal@radware.com"
    profile:
      
      name: hackazon-king-demo
      namespace: test
---
apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  annotations:
    radware/generationNumber: "2266"
    radware/protectionMode: IMMEDIATE
    radware/technology: BASIC
    radware/A: 99.199.294.99
    radware/CNAME: 23ddddddddddddddddfffff.v1.*****.net
    radware/ipRanges: 99.199.294.99
    radware/region: ASIA_SOUTHEAST_1
  name:  hackazon-king-demo
  namespace: test
  labels:
    release: hackazon-king-demo.com
spec:
  policies:
  - classifiers:
    - hostname: '*'
      id: classifier1
      path:
        operand: Prefix
        value: /
      protectionId: protection1
    name: hackazon-king-demo.com
    operatorEmail: support@radware.com
    protections:
    - activityTracking:
        blockPeriod: 1m
        opMode: Active
        rate: 100m    
      expressions:
        advExcludes:
        - parameter:
            name: ""
          path:
            value: /
          ruleIDs:
          - FSPA01
          - ATPANP
          - FSPA02
          
        opMode: Passive
      id: protection1
      signatures:
        advExcludes:
        - parameter:
            name: ""
          path:
            value: ""
          ruleIDs:
          - 10454
          zone: 
        - parameter:
            name: ""
          path:
            value: ""
          ruleIDs:
          - 6904
          zone: 
        - parameter:
            name: ""
          path:
            value: ""
          ruleIDs:
          - 10468
          zone: 
        - parameter:
            name: ""
          path:
            value: ""
          ruleIDs:
          - 10487
          zone: 
        - parameter:
            name: ""
          path:
            value: ""
          ruleIDs:
          - 9359
          zone: 
        - parameter:
            name: ""
          path:
            value: ""
          ruleIDs:
          - 9229
          zone: 
        opMode: Active
      whitelist:
        excludes:
        - isPatternRelative: false
          isRegex: False
          methods:
          - POST
          pattern: "/"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.woff"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.jpg"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.xml"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.htm"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.csv"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.gif"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.eot"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.xsl"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.pdf"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.pptx"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - POST
          pattern: "*.xml"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "/"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.js"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.do"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.doc"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.asp"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.bmp"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.jsp"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.axd"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.mp4"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - POST
          pattern: "*.no-extension"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.svg"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.wmv"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - POST
          pattern: "*.asp"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - POST
          pattern: "*.aspx"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.no-extension"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.php"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.ppt"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - POST
          pattern: "*.php"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.mp3"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.tif"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.png"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.shtml"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.ico"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - POST
          pattern: "*.jsp"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.zip"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.woff2"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.docx"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.html"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.jpeg"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.css"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.json"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.xlsx"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.aspx"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.xls"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.ttf"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - POST
          pattern: "*.json"
        
        - isPatternRelative: false
          isRegex: False
          methods:
          - GET
          pattern: "*.ashx"
        
        opMode: Active
---